question_data = [
    {"category": "Mythology", "type": "multiple", "difficulty": "medium",
     "question": "This Greek mythological figure is the god/goddess of battle strategy (among other things).",
     "correct_answer": "Athena",
     "incorrect_answers": ["Ares", "Artemis", "Apollo"]},
    {"category": "Mythology", "type": "multiple", "difficulty": "medium",
     "question": "Who was the Roman god of fire?",
     "correct_answer": "Vulcan",
     "incorrect_answers": ["Apollo", "Jupiter", "Mercury"]},
    {"category": "Mythology", "type": "multiple", "difficulty": "medium",
     "question": "Which of the following Mesopotamian mythological figures was NOT a deity?",
     "correct_answer": "Enkidu",
     "incorrect_answers": ["Enki", "Enlil", "Enkimdu"]},
    {"category": "Mythology", "type": "boolean", "difficulty": "medium",
     "question": "The Japanese god Izanagi successfully returned his wife Izanami from the Underworld.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Mythology", "type": "multiple", "difficulty": "medium",
     "question": "In Greek Mythology, who killed Achilles?",
     "correct_answer": "Paris",
     "incorrect_answers": ["Hector", "Helen", "Pericles"]},
    {"category": "Mythology", "type": "multiple", "difficulty": "medium",
     "question": "A minotaur is half human half what?",
     "correct_answer": "Bull",
     "incorrect_answers": ["Cow", "Horse", "Eagle"]},
    {"category": "Mythology", "type": "multiple", "difficulty": "medium",
     "question": "According to the Egyptian Myth of Osiris, who murdered Osiris?",
     "correct_answer": "Set",
     "incorrect_answers": ["Horus", "Ra", "Anhur"]},
    {"category": "Mythology", "type": "multiple", "difficulty": "medium",
     "question": "Which of the following is not one of the Greek Fates?",
     "correct_answer": "Narcissus",
     "incorrect_answers": ["Clotho", "Atropos", "Lachesis"]},
    {"category": "Mythology", "type": "multiple", "difficulty": "medium",
     "question": "Who is the god of war in Polynesian mythology?",
     "correct_answer": "&#039;Oro",
     "incorrect_answers": ["Hina", "Kohara", "M\u0101ui"]},
    {"category": "Mythology", "type": "multiple", "difficulty": "medium",
     "question": "What is the name of the Greek god of peaceful deaths?",
     "correct_answer": "Thanatos",
     "incorrect_answers": ["Tartarus", "Hades", "Moros"]}]
